### ISSUE TITLE
HostFlash messed up DNS?

### ISSUE THREAD

**Issue by dluxcru** [VR51/host-flash#2] opened 2019-02-22 03:37 UTC
The DNS on my linux machine seems to be messed up once I ran host flash. Chrome keeps saying DNS-PROBE-FINISHED-BAD-CONFIG, preventing any access to the internet. I am using Ubuntu 18.04. It did throw some kind of system internal error when I  ran host flash during DNS config. Help?

**Comment by dluxcru** [comment] 2019-02-22 03:39
I'd give you more details like outputs and logs, but hard to do that when relevant PC cannot access Internet.

**Comment by VR51** [comment] 2019-02-22 14:44
There are a couple of possible causes.

**One**

Host Flash flushes the DNS cache after the hosts file has been updated. It is possible the cache reset caused an issue.

Did you try restarting the computer and router?

**Two**

The other possibility is that the header from your hosts file was not copied properly into the replacement hosts file.

On your computer, browse to the directory called **/etc**. Look for the files **hosts** and **hosts.hf.original**. Compare the top section of both files, this is the section above the line **# Host Flash™ Firewall**.

The top of both files should look the same.

If they look different, copy and paste the top of **hosts.hf.original** over the top of **hosts** then restart the computer.

If they both look the same, restore the original hosts file by running Host Flash and choosing option 7 (Disable Host Flash™ list) then restart the computer. If this solves the problem then it's one or more rules in the hosts file that prevents you accessing the Internet.

**Four**

Are you using a proxy server/address to access the Internet? If so, remove the hosts rule that blocks access to the proxy server.

**Five**

The Redirect IP address might be incompatible with your OS. Run Host Flash and choose Option 3 ([0.0.0.0] - Change redirect IP address). Set the IP address to 127.0.0.1 then use Host Flash to rebuild and reinstall the hosts firewall. This will only be doable if host Flash is able to access the Internet to download the block lists.

--

Restoring the original hosts file and restarting the computer should fix any issues regardless of whether you can locate the specific cause of the issue experienced.

Keep me posted.

**Comment by dluxcru** [comment] 2019-03-01 07:44
Sorry that I have not had time to debug this further. College keeps me busy and thankfully the linux is my secondary device. 

1. I cannot restart the relevant router as I do not have access to it. Trying PC restart. No luck. 
. 
2.  It appears it didn't copy properly. Added in preceding lines. Restarted. No effect.
Proceeded with option 7 approach. Restarted. A local page on my own interal Apache server will now load. The same cannot be said for the rest of the internet. 

4. do not believe that there is a proxy server. Could be one somewhere on my school's network, would need a way to rule that out to be sure.

5. I set the redirect address to 127.0.0.1 on my very first run

**Comment by dluxcru** [comment] 2019-03-01 10:51
Restoring the origional hosts file seems to have fixed the problem. The larger problem is how to get Host-Flash to work? 

I'd include a paste-bin or something if it were small enough to post the whole text of the hosts file.

**Comment by VR51** [comment] 2019-03-01 11:33
Can you zip the compiled Host Flash hosts file and the original hosts file then mail them to me at lee [-at-] vr51 dot com. I'll see what I can make of them.

**Comment by VR51** [comment] 2019-04-14 14:40
This is resolved in the 3.1.4 version of Host Flash released today. The fault was caused by an oversight in the script code that stopped Host Flash copying any existing host file rules over to the new Host Flash built hosts file when Host Flash rules had not previously been installed before running. The oversight affected first time users only.

**Closed as completed by VR51** 2019-04-14 14:40 UTC
